title: Hetkumar Patel
description: As a recent graduate in Big Data, highly skilled and self-motivated in data visualization, project management, and Python. Proficiency in Excel, Tableau, and Power BI underscores the ability to translate intricate data into actionable insights. Demonstrating a proven record of effective leadership and innovation, dedication is focused on delivering impactful results and driving success for organizations.
theme: jekyll-theme-minimal
