title: Hetkumar Patel
logo: /images/Het_Passport_Photo_Resize.jpg
description: Recent Big Data graduate proficient in data visualization, project management, and Python. Skilled in Excel, Tableau, and Power BI. Strong track record of leadership and innovation, dedicated to delivering impactful results for organizations.
show_downloads: true
theme: jekyll-theme-minimal
